### ISSUE TITLE
Licensing issue (maybe)

### ISSUE THREAD

**Issue by poperigby** [Cutleast/Dynamic-Interface-Patcher#10]
Hi, just wanted to point out that because you're using CC-BY-NC-ND, because of the No Derivatives clause of the license, it's technically copyright infringement for people to contribute to this repository with pull requests. Did you intend for this?

**Comment by Cutleast** [comment]
Thanks for pointing this out! I chose the license a couple of years ago (don't remember the exact reasons) and just reused it.

I now replaced it by GNU General Public License v3.0.

**Comment by poperigby** [comment]
Thank you 🙂
